[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build completed with nixpacks.toml'"]

[start]
cmd = "./start.sh"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9" 